version: "3"
volumes:
  hexis-minecraft:
services:
  minecraft:
    image: "itzg/minecraft-server"
    environment:
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      EULA: "TRUE"
      VERSION: "1.14.4"
      ONLINE_MODE: "FALSE"
      INIT_MEMORY: "650M"
      MAX_MEMORY: "650M"
    ports:
      - "25565:25565"
    volumes:
      - hexis-minecraft:/data
