version: "3"
volumes:
  hexis-minecraft:
services:
  minecraft:    
    image: "itzg/minecraft-server:2018-1"
    environment:
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      ICON: "https://avatars3.githubusercontent.com/u/35294415?s=280&v=4"
      DIFFICULTY: "hard" 
      WORLD: "https://github.com/sj-freitas/hexis-craft/raw/master/hexis-craft/Hexis.zip"
      EULA: "TRUE"
      VERSION: "1.14.4"
      ONLINE_MODE: "FALSE"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "2G"
      LEVEL: "world"
      OPS: "SergioFreitas"
      MAX_PLAYERS: 64
    ports:
      - "25565:25565"
    volumes:
      - hexis-minecraft:/data
