version: "3"
volumes:
  hexis-minecraft:
services:
  minecraft:
    build: ./hexis-craft
    environment:
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      EULA: "TRUE"
      VERSION: "1.14.4"
      ONLINE_MODE: "FALSE"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "1G"
    ports:
      - "25565:25565"
    volumes:
      - hexis-minecraft:/data
